def compile_markdown_report(title: str, content: str) -> str:
    """
    Formulates a clean markdown document for file downloads.
    """
    md_doc = f"""# {title}

Generated by AI Career Copilot on behalf of the user.

---

{content}

---
*Confidentially processed via Google Gemini AI.*
"""
    return md_doc

def compile_html_document(title: str, content: str) -> str:
    """
    Generates a beautifully styled HTML page intended to be printed as a PDF.
    Uses clean typography, padding, and print margins.
    """
    # Replace newlines with HTML linebreaks or paragraphs for formatting
    paragraphs = content.split("\n\n")
    body_html = ""
    for p in paragraphs:
        if p.strip():
            # If the paragraph is a list
            if p.strip().startswith("-") or p.strip().startswith("*"):
                list_items = p.split("\n")
                li_html = "".join([f"<li>{item.strip()[1:].strip()}</li>" for item in list_items if item.strip()])
                body_html += f"<ul>{li_html}</ul>"
            else:
                body_html += f"<p>{p.strip().replace('\n', '<br>')}</p>"

    html_doc = f"""<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>{title}</title>
    <style>
        body {{
            font-family: 'Inter', -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, sans-serif;
            color: #1e293b;
            line-height: 1.6;
            margin: 40px;
            padding: 20px;
            background-color: #ffffff;
        }}
        h1 {{
            font-size: 24px;
            color: #0f172a;
            border-bottom: 2px solid #e2e8f0;
            padding-bottom: 10px;
            margin-bottom: 30px;
        }}
        p {{
            margin-bottom: 20px;
            font-size: 15px;
            text-align: justify;
        }}
        ul, ol {{
            margin-bottom: 20px;
            padding-left: 20px;
        }}
        li {{
            margin-bottom: 8px;
            font-size: 15px;
        }}
        .footer {{
            margin-top: 50px;
            font-size: 12px;
            color: #64748b;
            text-align: center;
            border-top: 1px solid #e2e8f0;
            padding-top: 15px;
        }}
        @media print {{
            body {{
                margin: 20px;
                padding: 0;
            }}
            .no-print {{
                display: none;
            }}
        }}
    </style>
</head>
<body>
    <h1>{title}</h1>
    <div class="content">
        {body_html}
    </div>
    <div class="footer">
        Generated by AI Career Copilot &bull; Verified via Applicant Tracking Systems &bull; Powered by Gemini
    </div>
    <script>
        // Auto trigger print dialogue when loaded inside browser
        // window.onload = function() {{ window.print(); }}
    </script>
</body>
</html>
"""
    return html_doc
